name: Test Dep-Server

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'pkg/dependency/**'
    - '.github/workflows/test-dependency-library.yml'
    - '.github/workflows/generate-dependency-workflows.yml'
    - '.github/workflows/*-get-new-versions.yml'
    - '.github/workflows/*-build-upload.yml'
    - '.github/workflows/*-test-upload-metadata.yml'
    - '.github/templates/**'
    - '.github/data/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test $(go list ./... | grep -v /pkg/dependency)

  approve:
    name: Auto Approve
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Approve
      uses: paketo-buildpacks/github-config/actions/pull-request/approve@main
      with:
        token: ${{ secrets.PAKETO_BOT_REVIEWER_GITHUB_TOKEN }}
        number: ${{ github.event.number }}
