name: Test and Deploy Dep-Server

on:
  push:
    branches: [ main ]

env:
  GAE_EMAIL: ${{ secrets.GAE_EMAIL }}
  GAE_KEY: ${{ secrets.GAE_KEY }}

jobs:

  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests
      run: go test -v ./...

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GAE_EMAIL }}
        service_account_key: ${{ secrets.GAE_KEY }}

    - name: Deploy Server
      run: gcloud app deploy
